spring:
  application:
    name: api-gateway
  # Config Server import disabled for local development
  # config:
  #   import: optional:configserver:http://course-platform-config:8888
  # profiles:
  #   active: docker
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
