spring:
  application:
    name: enrollmentservice
  config:
    import: optional:configserver:http://course-platform-config:8888
  profiles:
    active: docker

server:
  port: 8084
  servlet:
    context-path: /enrollment-service