spring:
  application:
    name: user-management-service
  config:
    import: optional:configserver:http://course-platform-config:8888
  profiles:
    active: docker

server:
  port: 8082
  servlet:
    context-path: /user-management-service
