spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_FIRST
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Use service discovery (lb://) for services registered in Eureka
        - id: user-management-service
          uri: lb://user-management-service
          predicates:
            - Path=/user-management-service/**
          filters:
            - name: RewritePath
              args:
                regexp: /user-management-service/(?<path>.*)
                replacement: /$\{path}
            - RemoveResponseHeader=Access-Control-Allow-Origin

        - id: course-management-service
          uri: lb://course-management-service
          predicates:
            - Path=/course-management-service/**
          filters:
            - name: RewritePath
              args:
                regexp: /course-management-service/(?<path>.*)
                replacement: /$\{path}

        - id: enrollment-service
          uri: lb://enrollmentservice
          predicates:
            - Path=/enrollment-service/**
          filters:
            - name: RewritePath
              args:
                regexp: /enrollment-service/(?<path>.*)
                replacement: /$\{path}

        - id: content-delivery-service
          uri: lb://content-delivery-service
          predicates:
            - Path=/content-delivery-service/**
          filters:
            - name: RewritePath
              args:
                regexp: /content-delivery-service/(?<path>.*)
                replacement: /$\{path}

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payment-service/**

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notification-service/**

eureka:
  client:
    service-url:
      defaultZone: http://course-platform-eureka:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8765

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics,gateway
  endpoint:
    health:
      show-details: always
